trigger: none

pool: my agent pool

steps: 
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'todo-service-connection'
    backendAzureRmStorageAccountName: 'todostorageaccount001'
    backendAzureRmContainerName: 'todocontainer'
    backendAzureRmKey: 'terraform.tfvars'

# REMOVE UsePythonVersion (self-hosted par nahi chalega)

- task: PowerShell@2
  displayName: Install Checkov
  inputs:
    script: |
      python --version
      pip install checkov

- task: PowerShell@2
  inputs:
    script: 'checkov -d $(System.DefaultWorkingDirectory) -o junitxml > result.xml'
