trigger: none

pool: my agent pool

steps: 
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'todo-service-connection'
    backendAzureRmStorageAccountName: 'todostorageaccount001'
    backendAzureRmContainerName: 'todocontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: CmdLine@2
  continueOnError: true
  inputs:
    script: 'tflint --chdir=$(System.DefaultWorkingDirectory) --recursive --format junit > tflint-report.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'tflint-report.xml'

- task: CmdLine@2
  inputs:
    script: 'checkov -d $(System.DefaultWorkingDirectory) -o junitxml > checkov-report.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'checkov-report.xml'
