trigger: none

pool: my agent pool

steps: 
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'todo-service-connection'
    backendAzureRmStorageAccountName: 'todostorageaccount001'
    backendAzureRmContainerName: 'todocontainer'
    backendAzureRmKey: 'terraform.tfvars'

# Python install (compulsory)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

# Single PowerShell task to install Checkov
- task: PowerShell@2
  displayName: "Install Checkov"
  inputs:
    targetType: 'inline'
    script: |
      python --version
      pip --version
      pip install checkov


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'checkov -d $(System.DefaultWorkingDirectory) -o junitxml > result.xml'

