trigger: none

pool: my agent pool

steps: 
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'todo-service-connection'
    backendAzureRmStorageAccountName: 'todostorageaccount001'
    backendAzureRmContainerName: 'todocontainer'
    backendAzureRmKey: 'terraform.tfvars'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'checkov -d "$(System.DefaultWorkingDirectory)" -o junitxml > result.xml'
