trigger: none

pool: my agent pool

steps: 
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'todo-service-connection'
    backendAzureRmStorageAccountName: 'todostorageaccount001'
    backendAzureRmContainerName: 'todocontainer'
    backendAzureRmKey: 'terraform.tfstate'


# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: 'checkov -d "$(System.DefaultWorkingDirectory)/environments" -o junitxml > result.xml'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install checkov
    checkov -v
  displayName: 'Install Checkov'

- script: |
    checkov -d "$(System.DefaultWorkingDirectory)" -o junitxml > checkov-report.xml
  displayName: 'Run Checkov'
